# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yuh/code/my/ldr-translator/gui/qt/ui_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from api import config, translate, tools
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/setting.svg"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 280)
        MainWindow.setMinimumSize(QtCore.QSize(360, 280))
        MainWindow.setMaximumSize(QtCore.QSize(600, 280))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(360, 280))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 280))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 18))
        self.label.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_ai = QtWidgets.QLabel(self.centralwidget)
        self.lb_ai.setMinimumSize(QtCore.QSize(60, 18))
        self.lb_ai.setMaximumSize(QtCore.QSize(60, 18))
        self.lb_ai.setOpenExternalLinks(False)
        self.lb_ai.setObjectName("lb_ai")
        self.horizontalLayout.addWidget(self.lb_ai)
        self.pte_ai = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_ai.setMinimumSize(QtCore.QSize(582, 30))
        self.pte_ai.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pte_ai.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pte_ai.setObjectName("pte_ai")
        self.horizontalLayout.addWidget(self.pte_ai)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 18))
        self.label_2.setMaximumSize(QtCore.QSize(60, 18))
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout1.addWidget(self.label_2)
        self.pte_sk1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_sk1.setMinimumSize(QtCore.QSize(582, 30))
        self.pte_sk1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pte_sk1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pte_sk1.setObjectName("pte_sk1")
        self.horizontalLayout1.addWidget(self.pte_sk1)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.btn_save1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save1.setObjectName("btn_save1")
        self.horizontalLayout2.addWidget(self.btn_save1)
        self.lb_msg_translate = QtWidgets.QLabel(self.centralwidget)
        self.lb_msg_translate.setText("")
        self.lb_msg_translate.setOpenExternalLinks(False)
        self.lb_msg_translate.setObjectName("lb_msg_translate")
        self.horizontalLayout2.addWidget(self.lb_msg_translate)
        spacerItem = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout2.addItem(spacerItem)
        self.lb_how_ai = QtWidgets.QLabel(self.centralwidget)
        self.lb_how_ai.setMinimumSize(QtCore.QSize(0, 18))
        self.lb_how_ai.setMaximumSize(QtCore.QSize(16777215, 18))
        self.lb_how_ai.setOpenExternalLinks(False)
        self.lb_how_ai.setObjectName("lb_how_ai")
        self.horizontalLayout2.addWidget(self.lb_how_ai)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 18))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setMinimumSize(QtCore.QSize(60, 18))
        self.label_21.setMaximumSize(QtCore.QSize(60, 18))
        self.label_21.setOpenExternalLinks(False)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout3.addWidget(self.label_21)
        self.pte_ak = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_ak.setEnabled(True)
        self.pte_ak.setMinimumSize(QtCore.QSize(0, 30))
        self.pte_ak.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pte_ak.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pte_ak.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pte_ak.setObjectName("pte_ak")
        self.horizontalLayout3.addWidget(self.pte_ak)
        self.verticalLayout.addLayout(self.horizontalLayout3)
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setMinimumSize(QtCore.QSize(0, 18))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_22.setOpenExternalLinks(False)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout4.addWidget(self.label_22)
        self.pte_sk2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_sk2.setMinimumSize(QtCore.QSize(0, 30))
        self.pte_sk2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pte_sk2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pte_sk2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pte_sk2.setObjectName("pte_sk2")
        self.horizontalLayout4.addWidget(self.pte_sk2)
        self.verticalLayout.addLayout(self.horizontalLayout4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save2.setObjectName("btn_save2")
        self.horizontalLayout_2.addWidget(self.btn_save2)
        self.lb_msg_ocr = QtWidgets.QLabel(self.centralwidget)
        self.lb_msg_ocr.setText("")
        self.lb_msg_ocr.setOpenExternalLinks(False)
        self.lb_msg_ocr.setObjectName("lb_msg_ocr")
        self.horizontalLayout_2.addWidget(self.lb_msg_ocr)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lb_how_ak = QtWidgets.QLabel(self.centralwidget)
        self.lb_how_ak.setOpenExternalLinks(False)
        self.lb_how_ak.setObjectName("lb_how_ak")
        self.horizontalLayout_2.addWidget(self.lb_how_ak)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "百度翻译设置"))
        self.label.setText(_translate("MainWindow", "翻译api"))
        self.lb_ai.setText(_translate("MainWindow", "AppId"))
        self.label_2.setText(_translate("MainWindow", "SecretKey"))
        self.btn_save1.setText(_translate("MainWindow", "保存"))
        self.lb_how_ai.setText(_translate("MainWindow", "如何获取"))
        self.label_3.setText(_translate("MainWindow", "图片识别api"))
        self.label_21.setText(_translate("MainWindow", "ApiKey"))
        self.label_22.setText(_translate("MainWindow", "SecretKey"))
        self.btn_save2.setText(_translate("MainWindow", "保存"))
        self.lb_how_ak.setText(_translate("MainWindow", "如何获取"))

        self.load_data()
        self._listen()

    def load_data(self):
        self.lb_how_ak.setOpenExternalLinks(True)
        self.lb_how_ai.setOpenExternalLinks(True)

        config_api = config.get_config_section(tools.server_baidu)

        self.pte_ai.setPlainText(config_api["translate_app_id"])
        self.pte_sk1.setPlainText(config_api["translate_secret_key"])
        self.pte_ak.setPlainText(config_api["ocr_api_key"])
        self.pte_sk2.setPlainText(config_api["ocr_secret_key"])

        url_translate = "<a href='" + config_api[
            "translate_url"] + "'>如何获取？</a>"
        url_ocr = "<a href='" + config_api["ocr_url"] + "'>如何获取？</a>"

        self.lb_how_ak.setText(url_translate)
        self.lb_how_ai.setText(url_ocr)

    def _listen(self):
        self.btn_save1.clicked.connect(self.save_baidu_translate)
        self.btn_save2.clicked.connect(self.save_baidu_ocr)

    def save_baidu_translate(self, btn=None):

        ok = False
        server = "baidu"
        text_a = self.pte_ai.toPlainText()
        text_b = self.pte_sk1.toPlainText()

        msg = "超时或账号密码错误"

        if (len(text_a) == 0 or len(text_b) == 0):
            msg = "已恢复默认（不推荐）"
        else:
            ok = translate.check_server_translate(server, text_a, text_b)
            if (ok):
                msg = "成功，已保存"
                config.set_config(server, "translate_app_id", text_a)
                config.set_config(server, "translate_secret_key", text_b)
        print(msg)
        self.lb_msg_translate.setText(msg)

    def save_baidu_ocr(self, btn=None):
        ok = False
        server = tools.server_baidu

        text_a = self.pte_ak.toPlainText()
        text_b = self.pte_sk2.toPlainText()

        msg = "超时或账号密码错误"

        if (len(text_a) == 0 or len(text_b) == 0):
            msg = "已恢复默认（不推荐）"
        else:
            ok = translate.check_server_ocr(server, text_a, text_b)
            if (ok):
                msg = "成功，已保存"
                config.set_config(server, "ocr_api_key", text_a)
                config.set_config(server, "ocr_secret_key", text_b)
                config.set_config(server, "access_token", "")
                config.set_config(server, "expires_in_date", 0)
        print(msg)
        self.lb_msg_ocr.setText(msg)
